# Tahap 1 – Membangun Case Base

Install Library

In [2]:
!pip install pdfplumber openpyxl -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.3/70.3 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 88.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 122.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 114.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 5.50.0 requires pillow<12.0,>=8.0, but you have pillow 12.2.0 which is incompatible.

Upload PDF

In [4]:
from google.colab import files

uploaded = files.upload()

Saving putusan_1_pid.sus-tpk_2026_pn_bdg_20260620195005.pdf to putusan_1_pid.sus-tpk_2026_pn_bdg_20260620195005.pdf
Saving putusan_2_pid.sus-tpk_2026_pn_bdg_20260620195343.pdf to putusan_2_pid.sus-tpk_2026_pn_bdg_20260620195343.pdf
Saving putusan_3_pid.sus-tpk_2026_pn_bdg_20260620195126.pdf to putusan_3_pid.sus-tpk_2026_pn_bdg_20260620195126.pdf
Saving putusan_5_pid.sus-tpk_2026_pn_bdg_20260620194922.pdf to putusan_5_pid.sus-tpk_2026_pn_bdg_20260620194922.pdf
Saving putusan_8_pid.sus-tpk_2026_pn_bdg_20260620194756.pdf to putusan_8_pid.sus-tpk_2026_pn_bdg_20260620194756.pdf
Saving putusan_10_pid.sus-tpk_2026_pn_bdg_20260620194509.pdf to putusan_10_pid.sus-tpk_2026_pn_bdg_20260620194509.pdf
Saving putusan_12_pid.sus-tpk_2026_pn_bdg_20260620195926.pdf to putusan_12_pid.sus-tpk_2026_pn_bdg_20260620195926.pdf
Saving putusan_14_pid.sus-tpk_2025_pn_bdg_20260619115139.pdf to putusan_14_pid.sus-tpk_2025_pn_bdg_20260619115139.pdf
Saving putusan_14_pid.sus-tpk_2026_pn_bdg_20260620200209.pdf to putusan_14_pid.sus-tpk_2026_pn_bdg_20260620200209.pdf
Saving putusan_16_pid.sus-tpk_2026_pn_bdg_20260620195608.pdf to putusan_16_pid.sus-tpk_2026_pn_bdg_20260620195608.pdf
Saving putusan_23_pid.sus-tpk_2026_pn_bdg_20260620200311.pdf to putusan_23_pid.sus-tpk_2026_pn_bdg_20260620200311.pdf
Saving putusan_24_pid.sus-tpk_2026_pn_bdg_20260620194046.pdf to putusan_24_pid.sus-tpk_2026_pn_bdg_20260620194046.pdf
Saving putusan_25_pid.sus-tpk_2026_pn_bdg_20260620170945.pdf to putusan_25_pid.sus-tpk_2026_pn_bdg_20260620170945.pdf
Saving putusan_26_pid.sus-tpk_2026_pn_bdg_20260620193947.pdf to putusan_26_pid.sus-tpk_2026_pn_bdg_20260620193947.pdf
Saving putusan_27_pid.sus-tpk_2026_pn_bdg_20260620194632.pdf to putusan_27_pid.sus-tpk_2026_pn_bdg_20260620194632.pdf
Saving putusan_28_pid.sus-tpk_2026_pn_bdg_20260620195756.pdf to putusan_28_pid.sus-tpk_2026_pn_bdg_20260620195756.pdf
Saving putusan_31_pid.sus-tpk_2025_pn_bdg_20260619192152.pdf to putusan_31_pid.sus-tpk_2025_pn_bdg_20260619192152.pdf
Saving putusan_32_pid.sus-tpk_2026_pn_bdg_20260619145358.pdf to putusan_32_pid.sus-tpk_2026_pn_bdg_20260619145358.pdf
Saving putusan_33_pid.sus-tpk_2025_pn_bdg_20260619192051.pdf to putusan_33_pid.sus-tpk_2025_pn_bdg_20260619192051.pdf
Saving putusan_34_pid.sus-tpk_2025_pn_bdg_20260619195023.pdf to putusan_34_pid.sus-tpk_2025_pn_bdg_20260619195023.pdf
Saving putusan_39_pid.sus-tpk_2025_pn_bdg_20260619191521.pdf to putusan_39_pid.sus-tpk_2025_pn_bdg_20260619191521.pdf
Saving putusan_40_pid.sus-tpk_2025_pn_bdg_20260619191730.pdf to putusan_40_pid.sus-tpk_2025_pn_bdg_20260619191730.pdf
Saving putusan_41_pid.sus-tpk_2025_pn_bdg_20260619192118.pdf to putusan_41_pid.sus-tpk_2025_pn_bdg_20260619192118.pdf
Saving putusan_43_pid.sus-tpk_2025_pn_bdg_20260619191814.pdf to putusan_43_pid.sus-tpk_2025_pn_bdg_20260619191814.pdf
Saving putusan_45_pid.sus-tpk_2025_pn_bdg_20260619191645.pdf to putusan_45_pid.sus-tpk_2025_pn_bdg_20260619191645.pdf
Saving putusan_46_pid.sus-tpk_2025_pn_bdg_20260619191956.pdf to putusan_46_pid.sus-tpk_2025_pn_bdg_20260619191956.pdf
Saving putusan_47_pid.sus-tpk_2025_pn_bdg_20260619192015.pdf to putusan_47_pid.sus-tpk_2025_pn_bdg_20260619192015.pdf
Saving putusan_50_pid.sus-tpk_2025_pn_bdg_20260619190900.pdf to putusan_50_pid.sus-tpk_2025_pn_bdg_20260619190900.pdf
Saving putusan_51_pid.sus-tpk_2025_pn_bdg_20260619190830.pdf to putusan_51_pid.sus-tpk_2025_pn_bdg_20260619190830.pdf
Saving putusan_63_pid.sus-tpk_2025_pn_bdg_20260619182114.pdf to putusan_63_pid.sus-tpk_2025_pn_bdg_20260619182114.pdf
Saving putusan_65_pid.sus-tpk_2025_pn_bdg_20260619182533.pdf to putusan_65_pid.sus-tpk_2025_pn_bdg_20260619182533.pdf
Saving putusan_69_pid.sus-tpk_2025_pn_bdg_20260619182139.pdf to putusan_69_pid.sus-tpk_2025_pn_bdg_20260619182139.pdf
Saving putusan_77_pid.sus-tpk_2025_pn_bdg_20260619182242.pdf to putusan_77_pid.sus-tpk_2025_pn_bdg_20260619182242.pdf
Saving putusan_87_pid.sus-tpk_2025_pn_bdg_20260619182324.pdf to putusan_87_pid.sus-tpk_2025_pn_bdg_20260619182324.pdf
Saving putusan_95_pid.sus-tpk_2025_pn_bdg_20260619182352.pdf to putusan_95_pid.sus-tpk_2025_pn_bdg_20260619182352.pdf
Saving putusan_96_pid.sus-tpk_2025_pn_bdg_20260619182415.pdf to putusan_96_pid.sus-tpk_2025_pn_bdg_20260619182415.pdf
Saving putusan_121_pid.sus-tpk_2025_pn_bdg_20260620193130.pdf to putusan_121_pid.sus-tpk_2025_pn_bdg_20260620193130.pdf
Saving putusan_142_pid.sus-tpk_2025_pn_bdg_20260620193508.pdf to putusan_142_pid.sus-tpk_2025_pn_bdg_20260620193508.pdf
Saving putusan_143_pid.sus-tpk_2025_pn_bdg_20260620193532.pdf to putusan_143_pid.sus-tpk_2025_pn_bdg_20260620193532.pdf
Saving putusan_144_pid.sus-tpk_2025_pn_bdg_20260620193658.pdf to putusan_144_pid.sus-tpk_2025_pn_bdg_20260620193658.pdf

Ekstraksi PDF → TXT

In [5]:
import os
import pdfplumber

data = []

for file in uploaded.keys():

    if file.lower().endswith(".pdf"):

        text = ""

        try:

            with pdfplumber.open(file) as pdf:

                for page in pdf.pages:

                    chars = []

                    for c in page.chars:

                        if c["size"] < 20:

                            chars.append(c)

                    page_text = "".join(
                        c["text"]
                        for c in chars
                    )

                    text += page_text + "\n"

            data.append({

                "nama_file": file,
                "isi_putusan": text

            })

            print(f"✓ {file}")

        except Exception as e:

            print(f"✗ {file} -> {e}")

✓ putusan_1_pid.sus-tpk_2026_pn_bdg_20260620195005.pdf
✓ putusan_2_pid.sus-tpk_2026_pn_bdg_20260620195343.pdf
✓ putusan_3_pid.sus-tpk_2026_pn_bdg_20260620195126.pdf
✓ putusan_5_pid.sus-tpk_2026_pn_bdg_20260620194922.pdf
✓ putusan_8_pid.sus-tpk_2026_pn_bdg_20260620194756.pdf
✓ putusan_10_pid.sus-tpk_2026_pn_bdg_20260620194509.pdf
✓ putusan_12_pid.sus-tpk_2026_pn_bdg_20260620195926.pdf
✓ putusan_14_pid.sus-tpk_2025_pn_bdg_20260619115139.pdf
✓ putusan_14_pid.sus-tpk_2026_pn_bdg_20260620200209.pdf
✓ putusan_16_pid.sus-tpk_2026_pn_bdg_20260620195608.pdf
✓ putusan_23_pid.sus-tpk_2026_pn_bdg_20260620200311.pdf
✓ putusan_24_pid.sus-tpk_2026_pn_bdg_20260620194046.pdf
✓ putusan_25_pid.sus-tpk_2026_pn_bdg_20260620170945.pdf
✓ putusan_26_pid.sus-tpk_2026_pn_bdg_20260620193947.pdf
✓ putusan_27_pid.sus-tpk_2026_pn_bdg_20260620194632.pdf
✓ putusan_28_pid.sus-tpk_2026_pn_bdg_20260620195756.pdf
✓ putusan_31_pid.sus-tpk_2025_pn_bdg_20260619192152.pdf
✓ putusan_32_pid.sus-tpk_2026_pn_bdg_20260619145358.pdf
✓ putusan_33_pid.sus-tpk_2025_pn_bdg_20260619192051.pdf
✓ putusan_34_pid.sus-tpk_2025_pn_bdg_20260619195023.pdf
✓ putusan_39_pid.sus-tpk_2025_pn_bdg_20260619191521.pdf
✓ putusan_40_pid.sus-tpk_2025_pn_bdg_20260619191730.pdf
✓ putusan_41_pid.sus-tpk_2025_pn_bdg_20260619192118.pdf
✓ putusan_43_pid.sus-tpk_2025_pn_bdg_20260619191814.pdf
✓ putusan_45_pid.sus-tpk_2025_pn_bdg_20260619191645.pdf
✓ putusan_46_pid.sus-tpk_2025_pn_bdg_20260619191956.pdf
✓ putusan_47_pid.sus-tpk_2025_pn_bdg_20260619192015.pdf
✓ putusan_50_pid.sus-tpk_2025_pn_bdg_20260619190900.pdf
✓ putusan_51_pid.sus-tpk_2025_pn_bdg_20260619190830.pdf
✓ putusan_63_pid.sus-tpk_2025_pn_bdg_20260619182114.pdf
✓ putusan_65_pid.sus-tpk_2025_pn_bdg_20260619182533.pdf
✓ putusan_69_pid.sus-tpk_2025_pn_bdg_20260619182139.pdf
✓ putusan_77_pid.sus-tpk_2025_pn_bdg_20260619182242.pdf
✓ putusan_87_pid.sus-tpk_2025_pn_bdg_20260619182324.pdf
✓ putusan_95_pid.sus-tpk_2025_pn_bdg_20260619182352.pdf
✓ putusan_96_pid.sus-tpk_2025_pn_bdg_20260619182415.pdf
✓ putusan_121_pid.sus-tpk_2025_pn_bdg_20260620193130.pdf
✓ putusan_142_pid.sus-tpk_2025_pn_bdg_20260620193508.pdf
✓ putusan_143_pid.sus-tpk_2025_pn_bdg_20260620193532.pdf
✓ putusan_144_pid.sus-tpk_2025_pn_bdg_20260620193658.pdf

Bentuk DataFrame

In [6]:
import pandas as pd

df = pd.DataFrame(data)

print(df.shape)

df.head()

(40, 2)

,nama_file,isi_putusan
0,putusan_1_pid.sus-tpk_2026_pn_bdg_202606201950...,Direktori Putusan Mahkamah Agung Republik Indo...
1,putusan_2_pid.sus-tpk_2026_pn_bdg_202606201953...,Direktori Putusan Mahkamah Agung Republik Indo...
2,putusan_3_pid.sus-tpk_2026_pn_bdg_202606201951...,Direktori Putusan Mahkamah Agung Republik Indo...
3,putusan_5_pid.sus-tpk_2026_pn_bdg_202606201949...,Direktori Putusan Mahkamah Agung Republik Indo...
4,putusan_8_pid.sus-tpk_2026_pn_bdg_202606201947...,Direktori Putusan Mahkamah Agung Republik Indo...

cleaning.

In [7]:
import re

def clean_putusan(text):

    text = str(text)

    text = re.sub(
        r"Direktori Putusan Mahkamah Agung Republik Indonesia",
        "",
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r"putusan\.mahkamahagung\.go\.id",
        "",
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r"Halaman\s+\d+\s+dari\s+\d+",
        "",
        text,
        flags=re.IGNORECASE
    )

    text = re.sub(
        r"Disclaimer.*?Telp\s*:\s*021-384\s*3348\s*\(ext\.318\)",
        "",
        text,
        flags=re.IGNORECASE | re.DOTALL
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()

Apply Cleaning

In [8]:
df["isi_putusan_clean"] = (
    df["isi_putusan"]
    .apply(clean_putusan)
)

print(
    df.iloc[0]["isi_putusan_clean"][:3000]
)

P U T U S A N Nomor 01/PID.SUS-TPK/2026/PN Bdg DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA Pengadilan Tindak Pidana Korupsi pada Pengadilan Negeri Bandung yang mengadili perkara pidana dengan acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai berikut dalam perkara Terdakwa: 1. Nama lengkap : EDE NURHIDAYAT Bin TATANG ABDULRAHMAN 2. Tempat lahir : Ciamis 3. Umur / Tgl. Lahir : 43 Tahun/ 23 Desember 1982 4. Jenis Kelamin : Laki - Laki 5. Kebangsaan : Indonesia 6. Tempat Tinggal : Lingkungan Siluman Baru, RT.003/RW.016 Kelurahan Purwaharja, Kecamatan Purwaharja, Kota Bandar 7. Agama : Islam 8. Pekerjaan : Perdagangan 9. Pendidikan : Strata 1 (S1) Terdakwa ditahan dalam tahanan Rumah Tahanan Negara oleh: - Penyidik : - sejak tanggal 02 Oktober 2025 sampai dengan tanggal 21 Oktober 2025; - Perpanjangan Penuntut Umum sejak tanggal 22 Oktober 2025 sampai dengan tanggal 30 Nopember 2025; - Perpanjangan Pertama Ketua Pengadilan Negeri Tasikmalaya sejak tanggal 01 Desember 2025 sampai dengan tanggal 30 Desember 2025; - Penuntut Umum : - sejak tanggal 31 Desember 2025 sampai dengan tanggal 19 Januari 2026; - Majelis Hakim : - sejak tanggal 15 januari 2026 sampai dengan tanggal 13 Februari 2026; - Perpanjangan Ketua Pengadilan Negeri Bandung sejak tanggal 14 Februari 2026 sampai dengan tanggal 14 April 2026; - Perpanjangan pertama Ketua Pengadilan Tinggi Halaman 1 Putusan Nomor 01/Pid.Sus-TPK/2026/PN.Bdg Bandung sejak tanggal 15 April 2026 sampai dengan tanggal 14 Mei 2026; - Perpanjangan kedua Ketua Tinggi Bandung sejak tanggal 15 Mei 2026 sampai dengan tanggal 13 Juni 2026. Terdakwa didampingi oleh Penasihat Hukum: 1). IMAM TANTHOWI JAUHARI, S.H.; 2). DEDI SUPRIADI, S.H.; 3). DIAN MULYADI E. M, S.H.; 4). AJAT MUNAJAT, S.H.; 5). ASEP ABDUL ROFIK, S.H., Advokat, Pengacara, pada kantor hukum IMAM TANTHOWI JAUHARI, yang beralamat kantor di Jalan Raya Mukhtamar Cipasung - Cipakat- Singaparna- Kabupaten Tasikmalaya Propinsi Jawa Barat, berdasarkan Surat Kuasa Khusus Nomor tertanggal 16 Januari 2026, sebagaimana didaftarkan pada tanggal 20 Januari 2026 dengan Nomor Registrasi: 9/SK/TPK/2026/PN.BDG; Pengadilan Negeri tersebut; Setelah membaca: 1. Penetapan Ketua Pengadilan Negeri Bandung Nomor: 01/Pid.Sus-TPK/2026/PN.Bdg tanggal 15 Januari 2026 tentang penunjukkan Majelis Hakim; 2. Penetapan Majelis Hakim Nomor: 01/Pid.Sus-TPK/2026/PN.Bdg tanggal 15 Januari 2026 tentang penetapan hari sidang; 3. Berkas perkara dan surat-surat lain yang bersangkutan; Setelah mendengar keterangan Saksi-saksi, Ahli dan Terdakwa serta memperhatikan bukti surat dan barang bukti yang diajukan di persidangan; Setelah mendengar pembacaan tuntutan pidana yang diajukan oleh Penuntut Umum yang pada pokoknya sebagai berikut: 1. Menyatakan Terdakwa EDE NURHIDAYAT Bin TATANG ABDULRAHMAN tidak terbukti bersalah “melakukan tindak pidana korupsi” secara bersama-sama sebagaimana diatur dan diancam pidana dalam Pasal 603 Undang-Undang Nomor 1 Tahun 2023 tentang Kitab Und

Cek hasil.

In [9]:
for i in range(3):

    print("="*100)

    print(
        df.iloc[i]["nama_file"]
    )

    print(
        df.iloc[i]["isi_putusan_clean"][:1500]
    )

====================================================================================================
putusan_1_pid.sus-tpk_2026_pn_bdg_20260620195005.pdf
P U T U S A N Nomor 01/PID.SUS-TPK/2026/PN Bdg DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA Pengadilan Tindak Pidana Korupsi pada Pengadilan Negeri Bandung yang mengadili perkara pidana dengan acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai berikut dalam perkara Terdakwa: 1. Nama lengkap : EDE NURHIDAYAT Bin TATANG ABDULRAHMAN 2. Tempat lahir : Ciamis 3. Umur / Tgl. Lahir : 43 Tahun/ 23 Desember 1982 4. Jenis Kelamin : Laki - Laki 5. Kebangsaan : Indonesia 6. Tempat Tinggal : Lingkungan Siluman Baru, RT.003/RW.016 Kelurahan Purwaharja, Kecamatan Purwaharja, Kota Bandar 7. Agama : Islam 8. Pekerjaan : Perdagangan 9. Pendidikan : Strata 1 (S1) Terdakwa ditahan dalam tahanan Rumah Tahanan Negara oleh: - Penyidik : - sejak tanggal 02 Oktober 2025 sampai dengan tanggal 21 Oktober 2025; - Perpanjangan Penuntut Umum sejak tanggal 22 Oktober 2025 sampai dengan tanggal 30 Nopember 2025; - Perpanjangan Pertama Ketua Pengadilan Negeri Tasikmalaya sejak tanggal 01 Desember 2025 sampai dengan tanggal 30 Desember 2025; - Penuntut Umum : - sejak tanggal 31 Desember 2025 sampai dengan tanggal 19 Januari 2026; - Majelis Hakim : - sejak tanggal 15 januari 2026 sampai dengan tanggal 13 Februari 2026; - Perpanjangan Ketua Pengadilan Negeri Bandung sejak tanggal 14 Februari 2026 sampai dengan tanggal 14 April 2026; - Perpanjangan pertama Ketua Pengadilan Tinggi Halaman 1 Putusan Nomor 01/Pid.Sus-TPK/2026/PN.Bdg Bandung sejak tanggal 15 April 2026 sampai dengan tangg
====================================================================================================
putusan_2_pid.sus-tpk_2026_pn_bdg_20260620195343.pdf
Putusan Nomor 02 /Pid.Sus-TPK/2026/PN Bdg P U T U S A N Nomor 02/PID.SUS-TPK/2026/PN Bdg DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA Pengadilan Tindak Pidana Korupsi pada Pengadilan Negeri Bandung yang mengadili perkara pidana dengan acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai berikut dalam perkara Terdakwa: 1. Nama lengkap : AAN HANAFI, S.Ag., M.Pd. Bin Alm. OYO SUBAGJA 2. Tempat lahir : Banjar 3. Umur / Tgl. Lahir : 50 tahun/09 Oktober 1974 4. Jenis Kelamin : Laki - Laki 5. Kebangsaan : Indonesia 6. Tempat Tinggal : Dusun Pangasinan, RT. 002/RW. 007, Desa Binangun, Kecamatan Pataruman, Kota Banjar, Provinsi Jawa Barat 7. Agama : Islam 8. Pekerjaan : Wiraswasta 9. Pendidikan : S2 Terdakwa ditahan dalam Rumah Tahanan Negara oleh: - Penyidik : - sejak tanggal 02 Oktober 2025 sampai dengan tanggal 21 Oktober 2025; - Perpanjangan Penuntut Umum sejak tanggal 22 Oktober 2025 sampai dengan tanggal 30 Nopember 2025; - Perpanjangan Pertama Ketua Pengadilan Negeri Tasikmalaya sejak tanggal 01 Desember 2025 sampai dengan tanggal 30 Desember 2025; - Penuntut Umum : - sejak tanggal 31 Desember 2025 sampai dengan tanggal 19 Januari 2026; - Majelis Hakim : - sejak tanggal 15 januari 2026 sampai dengan tanggal 13 Februari 2026; - Perpanjangan Ketua Pengadilan Negeri Bandung sejak tanggal 14 Februari 2026 sampai Halaman 1 Putusan Nomor 02 /Pid.Sus-TPK/2026/PN Bdg dengan tanggal 14 April 2026; - Perpanjangan pertama Ketua Pengadilan Tinggi Bandung sejak tan
====================================================================================================
putusan_3_pid.sus-tpk_2026_pn_bdg_20260620195126.pdf
P U T U S A N Nomor 03/PID.SUS-TPK/2026/PN Bdg DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA Pengadilan Tindak Pidana Korupsi pada Pengadilan Negeri Bandung yang mengadili perkara pidana dengan acara pemeriksaan biasa dalam tingkat pertama menjatuhkan putusan sebagai berikut dalam perkara Terdakwa: 1. Nama lengkap : ELAN SUHERLAN Bin (Alm) IDI SUTADI 2. Tempat lahir : Ciamis 3. Umur / Tgl. Lahir : 54 tahun / 31 Agustus 1971 4. Jenis Kelamin : Laki - Laki 5. Kebangsaan : Indonesia 6. Tempat Tinggal : Dusun Cinangka, RT.004/RW.007 Desa Sukasetia Kecamatan Cihaurbeti Kabupaten Tasikmalaya 7. Agama : Islam 8. Pekerjaan : Wiraswasta 9. Pendidikan : SMA Terdakwa ditahan dalam Rumah Tahanan Negara oleh: - Penyidik : - sejak tanggal 02 Oktober 2025 sampai dengan tanggal 21 Oktober 2025; - Perpanjangan Penuntut Umum sejak tanggal 22 Oktober 2025 sampai dengan tanggal 30 Nopember 2025; - Perpanjangan Pertama Ketua Pengadilan Negeri Tasikmalaya sejak tanggal 01 Desember 2025 sampai dengan tanggal 30 Desember 2025; - Penuntut Umum : - sejak tanggal 31 Desember 2025 sampai dengan tanggal 19 Januari 2026; - Majelis Hakim : - sejak tanggal 15 januari 2026 sampai dengan tanggal 13 Februari 2026; Terdakwa didampingi oleh Penasihat Hukum: 1). IMAM TANTHOWI JAUHARI, S.H.; 2). DEDI SUPRIADI, S.H.; 3). DIAN MULYADI E. M, S.H.; 4). AJAT MUNAJAT, S.H.; 5). ASEP ABDUL ROFIK, S.H., Advokat, Pengacara, pada kantor hukum IMAM TANTHOWI JAUHARI, yang beralamat kantor di Jalan Halaman 1 Putusan Nomor

Panjang Dokumen

In [10]:
df["panjang_clean"] = (
    df["isi_putusan_clean"]
    .str.len()
)

print(
    df["panjang_clean"]
    .describe()
)

count    4.000000e+01
mean     7.684936e+05
std      4.480552e+05
min      2.622870e+05
25%      4.672608e+05
50%      7.060770e+05
75%      9.101725e+05
max      2.342037e+06
Name: panjang_clean, dtype: float64

Cek Dokumen Bermasalah

In [11]:
df[
    df["panjang_clean"] < 100
]

Empty DataFrame
Columns: [nama_file, isi_putusan, isi_putusan_clean, panjang_clean]
Index: []